### ISSUE TITLE
Clean command throws erros

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#339]
```

   _____ _
  / ____| |
 | (___ | |__   ___  _ __  _   _  ___
  \___ \| '_ \ / _ \| '_ \| | | |/ _ \
  ____) | | | | (_) | |_) | |_| | (_) |
 |_____/|_| |_|\___/| .__/ \__, |\___/
                    | |     __/ |
                    |_|    |___/
Copyright 2021

[x] all tables dropped
[x] __pycache__ successfully deleted
[x] file 'shopyo.db' successfully deleted
Traceback (most recent call last):
  File "manage.py", line 68, in <module>
    process()
  File "C:\Users\j\Desktop\entry\git\shopyo\venv\lib\site-packages\click\core.py", line 829, in __ca
ll__
    return self.main(*args, **kwargs)
  File "C:\Users\j\Desktop\entry\git\shopyo\venv\lib\site-packages\click\core.py", line 782, in main

    rv = self.invoke(ctx)
  File "C:\Users\j\Desktop\entry\git\shopyo\venv\lib\site-packages\click\core.py", line 1066, in inv
oke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\j\Desktop\entry\git\shopyo\venv\lib\site-packages\click\core.py", line 610, in invo
ke
    return callback(*args, **kwargs)
  File "manage.py", line 27, in process
    clean()
  File "C:\Users\j\Desktop\entry\git\shopyo\shopyo\shopyoapi\cmd.py", line 50, in clean
    remove_file_or_dir("migrations")
  File "C:\Users\j\Desktop\entry\git\shopyo\shopyo\shopyoapi\cmd_helper.py", line 37, in remove_file
_or_dir
    rmtree(name)
  File "C:\Users\j\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 731, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\j\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 613, in _rmtree_un
safe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\j\AppData\Local\Programs\Python\Python38-32\lib\shutil.py", line 611, in _rmtree_un
safe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'migrations'
```

Was fine when i rerun command

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ I am unable to reproduce the bug. Can you maybe follow this bug report template(https://gist.github.com/carlo/3402842) to help me reproduce the bug? Also what python version are you using?

**Comment by rehmanis** [comment]
@Abdur-rahmaanJ can you run clean and initialize a few times to see if you still see this issue? #345 might have fixed this but not sure.
